version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.16.1
      - run:
          name: Build application Docker images
          command: |
            docker-compose build
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose -f ./docker-compose.test.yml up --exit-code-from test
      - deploy:
          name: Push application Docker image
          command: |
            [[ -z $CIRCLE_TAG ]] && exit 0
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            docker tag ropelive/twine ropelive/twine:$CIRCLE_TAG
            docker push ropelive/twine:$CIRCLE_TAG

# this step is required for CircleCI to understand that a tag is pushed - otherwise they don't start a build 
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"